package web

data class ExamplesConfig(val minExample:Int = 0, val maxExample:Int = 568)

fun getExampleState(exampleToRun:Int):Phaser.State {
    return when(exampleToRun){
        0->examples.animation.AnimationEvents()
        1->examples.animation.ChangeFrame()
        2->examples.animation.ChangeTextureOnClick()
        3->examples.animation.DestroyAnimation()
        4->examples.animation.DynamicAnimation()
        5->examples.animation.FrameUpdate()
        6->examples.animation.GroupCreation()
        7->examples.animation.LoadTexture()
        8->examples.animation.LocalJsonObject()
        9->examples.animation.LoopedAnimation()
        10->examples.animation.MultipleAnims()
        11->examples.animation.SpriteSheet()
        12->examples.animation.StarlingAtlas()
        13->examples.animation.StopAnimation()
        14->examples.animation.TwoFrameTest()
        15->examples.arcadephysics.AccelerateToPointer()
        16->examples.arcadephysics.AngleBetween()
        17->examples.arcadephysics.AngleToPointer()
        18->examples.arcadephysics.AngularAcceleration()
        19->examples.arcadephysics.AngularVelocity()
        20->examples.arcadephysics.AsteroidsMovement()
        21->examples.arcadephysics.BodyDebug()
        22->examples.arcadephysics.BodyEnable()
        23->examples.arcadephysics.BodyScale()
        24->examples.arcadephysics.Bounce()
        25->examples.arcadephysics.BounceAccelerator()
        26->examples.arcadephysics.BounceKnock()
        27->examples.arcadephysics.BounceWithGravity()
        28->examples.arcadephysics.BoundingBox()
        29->examples.arcadephysics.CircleBody()
        30->examples.arcadephysics.DirectBodyMovement()
        31->examples.arcadephysics.DistanceToPointer()
        32->examples.arcadephysics.GlobalPause()
        33->examples.arcadephysics.Gravity()
        34->examples.arcadephysics.GravityAndDrag()
        35->examples.arcadephysics.GroupVsGroup()
        36->examples.arcadephysics.GroupVsSelf()
        37->examples.arcadephysics.LargerBoundingBox()
        38->examples.arcadephysics.Launcher()
        39->examples.arcadephysics.LauncherFollow()
        40->examples.arcadephysics.LauncherFollowWorld()
        41->examples.arcadephysics.MassVelocityTest()
        42->examples.arcadephysics.MoveOverDistance()
        43->examples.arcadephysics.MoveToPointer()
        44->examples.arcadephysics.MoveTowardsObject()
        45->examples.arcadephysics.MultiAngleToPointer()
        46->examples.arcadephysics.Multiball()
        47->examples.arcadephysics.NestedGroup()
        48->examples.arcadephysics.OffsetBoundingBox()
        49->examples.arcadephysics.OnCollideEvent()
        50->examples.arcadephysics.OneWayCollision()
        51->examples.arcadephysics.PlatformerBasics()
        52->examples.arcadephysics.PlatformerTight()
        53->examples.arcadephysics.ProcessCallback()
        54->examples.arcadephysics.QuadtreeCollisionInfos()
        55->examples.arcadephysics.RotateToSprite()
        56->examples.arcadephysics.ShipTrail()
        57->examples.arcadephysics.ShootThePointer()
        58->examples.arcadephysics.Snake()
        59->examples.arcadephysics.SortDirection()
        60->examples.arcadephysics.SortDirectionVertical()
        61->examples.arcadephysics.SpriteVsGroup()
        62->examples.arcadephysics.SpriteVsSprite()
        63->examples.arcadephysics.VerticalCollision()
        64->examples.arcadephysics.WorldBoundsEvent()
        65->examples.audio.AudioSpriteDuration()
        66->examples.audio.AudioSpriteExample()
        67->examples.audio.AudioSpriteJson()
        68->examples.audio.FadeIn()
        69->examples.audio.Ios()
        70->examples.audio.Loop()
        71->examples.audio.PauseAndResume()
        72->examples.audio.PauseAndResumeMarker()
        73->examples.audio.PlayMusic()
        74->examples.audio.RemoveSound()
        75->examples.audio.RestartSound()
        76->examples.audio.SoundComplete()
        77->examples.basics.E01LoadAnImage()
        78->examples.basics.E02ClickOnAnImage()
        79->examples.basics.E03MoveAnImage()
        80->examples.basics.E04ImageFollowInput()
        81->examples.basics.E05LoadAnAnimation()
        82->examples.basics.E06RenderText()
        83->examples.basics.E07TweenAnImage()
        84->examples.basics.E08SpriteRotation()
        85->examples.bitmapdata.AlphaMask()
        86->examples.bitmapdata.Atlas()
        87->examples.bitmapdata.CopyBitmapdata()
        88->examples.bitmapdata.CopyPixels()
        89->examples.bitmapdata.DrawAtlasFrame()
        90->examples.bitmapdata.DrawGroup()
        91->examples.bitmapdata.DrawSprite()
        92->examples.bitmapdata.GetPixel()
        93->examples.bitmapdata.ReplaceColor()
        94->examples.bitmapdata.SetHsl()
        95->examples.bitmapdata.SpriteTexture()
        96->examples.bitmapdata.TextExample()
        97->examples.bitmapdata.Tint()
        98->examples.buttons.ActionOnClick()
        99->examples.buttons.ButtonInAGroup()
        100->examples.buttons.ButtonScale()
        101->examples.buttons.ButtonUsingTextureAtlas()
        102->examples.buttons.CancelButton()
        103->examples.buttons.ChangingTheFrames()
        104->examples.buttons.DisableButtonOnClick()
        105->examples.buttons.RotatedButtons()
        106->examples.camera.BasicFollow()
        107->examples.camera.CameraCull()
        108->examples.camera.CameraFade()
        109->examples.camera.CameraFlash()
        110->examples.camera.CameraLerp()
        111->examples.camera.CameraShake()
        112->examples.camera.CameraView()
        113->examples.camera.Deadzone()
        114->examples.camera.FixedToCamera()
        115->examples.camera.FollowStyles()
        116->examples.camera.MassCameraCull()
        117->examples.camera.MovingTheCamera()
        118->examples.camera.SmoothFollow()
        119->examples.camera.WorldSprite()
        120->examples.camera.ZoomingTheCamera()
        121->examples.create.GenerateSprite()
        122->examples.create.MoreSprites()
        123->examples.create.RatAttack()
        124->examples.debug.DebugCamera()
        125->examples.debug.DebugDisplay()
        126->examples.debug.DebugDraw()
        127->examples.debug.DebugInput()
        128->examples.debug.DebugPhysics()
        129->examples.debug.DebugSprite()
        130->examples.demoscene.AtariIntro()
        131->examples.demoscene.FontFromBitmapdata()
        132->examples.demoscene.RasterCarpet()
        133->examples.demoscene.RasterFont()
        134->examples.demoscene.Springy()
        135->examples.demoscene.Starfield()
        136->examples.demoscene.UnlimitedBobs()
        137->examples.display.Arc()
        138->examples.display.ArcadePhysicsGraphicsShape()
        139->examples.display.ArcDetails()
        140->examples.display.CircleExample()
        141->examples.display.Ellipse()
        142->examples.display.ExtractMask()
        143->examples.display.Fullscreen()
        144->examples.display.FullscreenButtons()
        145->examples.display.GameBackgroundColor()
        146->examples.display.GenerateTextureFromGraphics()
        147->examples.display.Gradient()
        148->examples.display.Graphics2()
        149->examples.display.GraphicsChild()
        150->examples.display.GraphicsExample()
        151->examples.display.GraphicsInputEvents()
        152->examples.display.GraphicsPerf()
        153->examples.display.HsvColorWheel()
        154->examples.display.PixiRenderTexture()
        155->examples.display.RenderCrisp()
        156->examples.display.RenderTextureImage()
        157->examples.display.RenderTextureMirror()
        158->examples.display.RenderTextureRotation()
        159->examples.display.RenderTextureTilemap()
        160->examples.display.RenderTextureToTilesprite()
        161->examples.display.RenderTextureTrail()
        162->examples.display.RoundPixels()
        163->examples.display.SpriteShadow()
        164->examples.display.SpritesheetFromGraphics()
        165->examples.display.TintSprite()
        166->examples.display.TintSpriteFrame()
        167->examples.display.Viewport()
        168->examples.filters.Bacteria()
        169->examples.filters.Basic()
        170->examples.filters.BlueDots()
        171->examples.filters.Blur()
        172->examples.filters.CheckerWave()
        173->examples.filters.Dalek()
        174->examples.filters.Dotwave()
        175->examples.filters.Dotwave2()
        176->examples.filters.Fire()
        177->examples.filters.Fireball()
        178->examples.filters.Gray()
        179->examples.filters.Kaleidoscope()
        180->examples.filters.Lightbeams()
        181->examples.filters.Lightwave()
        182->examples.filters.Marble()
        183->examples.filters.MouseRay()
        184->examples.filters.MouseWave()
        185->examples.filters.MultipleShaders()
        186->examples.filters.Pixelate()
        187->examples.filters.PixiFilter()
        188->examples.filters.PlaneDeformation()
        189->examples.filters.Plasma()
        190->examples.filters.RainbowBars()
        191->examples.filters.RetroPlasma()
        192->examples.filters.Rotozoomer()
        193->examples.filters.Seascape()
        194->examples.filters.Sinewave()
        195->examples.filters.SinewaveFixedBase()
        196->examples.filters.SphereTracer()
        197->examples.filters.SpiralGalaxy()
        198->examples.filters.StarfieldFilterExample()
        199->examples.filters.Starlight()
        200->examples.filters.Tunnel()
        201->examples.filters.Undersea()
        202->examples.filters.VduNoise()
        203->examples.filters.VerticalBars()
        204->examples.filters.Vortex()
        205->examples.filters.WorldFilter()
        206->examples.games.Breakout()
        207->examples.games.Defender()
        208->examples.games.Gemmatch()
        209->examples.games.Invaders()
        210->examples.games.MatchingPairs()
        211->examples.games.Simon()
        212->examples.games.SlidingPuzzle()
        213->examples.games.Starstruck()
        214->examples.games.Tanks()
        215->examples.games.Yahtzee()
        216->examples.geometry.CenterLine()
        217->examples.geometry.Centroid()
        218->examples.geometry.CircleExample()
        219->examples.geometry.CircleRandomPoint()
        220->examples.geometry.EllipseRandomPoint()
        221->examples.geometry.LineBounds()
        222->examples.geometry.LineExample()
        223->examples.geometry.LineIntersection()
        224->examples.geometry.LineMidpoint()
        225->examples.geometry.LineRandomPoint()
        226->examples.geometry.LineReflection()
        227->examples.geometry.PlayingWithPoints()
        228->examples.geometry.PolygonContains()
        229->examples.geometry.PolygonExample()
        230->examples.geometry.QuadtreeExample()
        231->examples.geometry.RectangleExample()
        232->examples.geometry.RectangleGetPoint()
        233->examples.geometry.RectangleIntersects()
        234->examples.geometry.RectangleRandomPoint()
        235->examples.geometry.RotateLine()
        236->examples.geometry.RotatePoint()
        237->examples.groups.AddASpriteToGroup()
        238->examples.groups.AlignFramesToGrid()
        239->examples.groups.AlignSpritesToGrid()
        240->examples.groups.BringAGroupToTop()
        241->examples.groups.CallAll()
        242->examples.groups.CallAllAnimations()
        243->examples.groups.CallAllInput()
        244->examples.groups.CreateGroup()
        245->examples.groups.CreateIfNull()
        246->examples.groups.CreateSpriteInAGroup()
        247->examples.groups.CreateThumbnail()
        248->examples.groups.DepthSort()
        249->examples.groups.DisplayOrder()
        250->examples.groups.FilterByProperty()
        251->examples.groups.ForEach()
        252->examples.groups.GetFirst()
        253->examples.groups.GetFirstDead()
        254->examples.groups.GroupAsLayer()
        255->examples.groups.GroupBounds()
        256->examples.groups.GroupScale()
        257->examples.groups.GroupTransform()
        258->examples.groups.GroupTransformRotate()
        259->examples.groups.GroupTransformTween()
        260->examples.groups.HasProperty()
        261->examples.groups.MoveToAnotherGroup()
        262->examples.groups.NestedGroups()
        263->examples.groups.Recycling()
        264->examples.groups.Remove()
        265->examples.groups.RemoveBetween()
        266->examples.groups.RemoveCheck()
        267->examples.groups.Replace()
        268->examples.groups.SetAll()
        269->examples.groups.Sort()
        270->examples.groups.SubGroupsGroupLength()
        271->examples.groups.SwapChildrenInAGroup()
        272->examples.input.BoundsRect()
        273->examples.input.BoundsSprite()
        274->examples.input.BringAChildToTop()
        275->examples.input.ButtonDestroy()
        276->examples.input.ButtonOpenPopup()
        277->examples.input.CursorKeyMovement()
        278->examples.input.DownDuration()
        279->examples.input.Drag()
        280->examples.input.DragEventParameters()
        281->examples.input.DragScaledGroup()
        282->examples.input.DragSeveralSprites()
        283->examples.input.DragUpdate()
        284->examples.input.DragUpdateMultiple()
        285->examples.input.DropLimitation()
        286->examples.input.FollowMouse()
        287->examples.input.Gamepad()
        288->examples.input.GamepadAnalogButton()
        289->examples.input.GamepadButtons()
        290->examples.input.GamepadMultiplePads()
        291->examples.input.GameScale()
        292->examples.input.GroupInputEvents()
        293->examples.input.IgnoreChildInput()
        294->examples.input.InputChildPriority()
        295->examples.input.InputEnableGroup()
        296->examples.input.InputOrder()
        297->examples.input.InputPriority()
        298->examples.input.Keyboard()
        299->examples.input.KeyboardHotkeys()
        300->examples.input.KeyboardJustpressed()
        301->examples.input.KeyExample()
        302->examples.input.MotionLockHorizontal()
        303->examples.input.MotionLockVertical()
        304->examples.input.MouseButtons()
        305->examples.input.MultiTouch()
        306->examples.input.OnTap()
        307->examples.input.OutOfGame()
        308->examples.input.OutOfGameMouseUp()
        309->examples.input.OverrideDefaultControls()
        310->examples.input.PixelPerfectClickDetection()
        311->examples.input.PixelpickAtlas()
        312->examples.input.PixelpickAtlasScaled()
        313->examples.input.PixelpickScrollingEffect()
        314->examples.input.PixelpickSpritesheet()
        315->examples.input.PointerOver()
        316->examples.input.SnapOnDrag()
        317->examples.input.TouchEvents()
        318->examples.input.WordInput()
        319->examples.loader.AssetPack()
        320->examples.loader.CheckCache()
        321->examples.loader.LoadAudio()
        322->examples.loader.LoadBitmapFont()
        323->examples.loader.LoadImage()
        324->examples.loader.LoadJsonFile()
        325->examples.loader.LoadSpritesheet()
        326->examples.loader.LoadStarlingAtlas()
        327->examples.loader.LoadTextFile()
        328->examples.loader.LoadTextureAtlas()
        329->examples.loader.LoadTilemapJson()
        330->examples.loader.LoadVideo()
        331->examples.loader.LoadXmlFile()
        332->examples.loader.PickImagesFromCache()
        333->examples.misc.AntialiasGame()
        334->examples.misc.Device()
        335->examples.misc.GameConfig()
        336->examples.misc.Net()
        337->examples.misc.PauseMenu()
        338->examples.misc.RandomGenerators()
        339->examples.misc.RepeatableRandomNumbers()
        340->examples.misc.Template()
        341->examples.misc.WeightedPick()
        342->examples.p2physics.Aabb()
        343->examples.p2physics.AccelerateToObject()
        344->examples.p2physics.BasicMovement()
        345->examples.p2physics.BodyClick()
        346->examples.p2physics.BodyDebug()
        347->examples.p2physics.CollideWorldBounds()
        348->examples.p2physics.CollisionGroups()
        349->examples.p2physics.ContactEvents()
        350->examples.p2physics.ContactMaterial()
        351->examples.p2physics.DistanceConstraint()
        352->examples.p2physics.GearConstraint()
        353->examples.p2physics.Gravity()
        354->examples.p2physics.GravityScale()
        355->examples.p2physics.ImpactEvents()
        356->examples.p2physics.KillAndRevive()
        357->examples.p2physics.KinematicBody()
        358->examples.p2physics.LoadPolygon1()
        359->examples.p2physics.LoadPolygon2()
        360->examples.p2physics.LoadPolygon3()
        361->examples.p2physics.LockConstraint()
        362->examples.p2physics.MouseSpring()
        363->examples.p2physics.MovementConstraint()
        364->examples.p2physics.PhysicsGroup()
        365->examples.p2physics.PickUpObject()
        366->examples.p2physics.PlatformerMaterial()
        367->examples.p2physics.PostbroadphaseCallback()
        368->examples.p2physics.PrismaticConstraint()
        369->examples.p2physics.RemoveSpring()
        370->examples.p2physics.RevoluteConstraintExample()
        371->examples.p2physics.Springs()
        372->examples.p2physics.StaticBody()
        373->examples.p2physics.Thrust()
        374->examples.p2physics.ThrustLeftRight()
        375->examples.p2physics.TilemapExample()
        376->examples.p2physics.TilemapGravity()
        377->examples.p2physics.TilespriteExample()
        378->examples.p2physics.WorldBoundary()
        379->examples.p2physics.WorldMove()
        380->examples.particles.AutoScale()
        381->examples.particles.ClickBurst()
        382->examples.particles.Collision()
        383->examples.particles.DestroyEmitter()
        384->examples.particles.DiamondBurst()
        385->examples.particles.EmitterWidth()
        386->examples.particles.Firestarter()
        387->examples.particles.Flow()
        388->examples.particles.Glass()
        389->examples.particles.NoRotation()
        390->examples.particles.ParticleAlpha()
        391->examples.particles.ParticleScale()
        392->examples.particles.ParticlesVsPlatforms()
        393->examples.particles.Rain()
        394->examples.particles.RandomSprite()
        395->examples.particles.SmokeTrail()
        396->examples.particles.Snow()
        397->examples.particles.TweenedEmitter()
        398->examples.particles.WhenParticlesCollide()
        399->examples.particles.WorldParticles()
        400->examples.particles.ZeroGravity()
        401->examples.sprites.AddAnImage()
        402->examples.sprites.AddASprite()
        403->examples.sprites.AddSeveralSprites()
        404->examples.sprites.AlignInRectangle()
        405->examples.sprites.AlignMultipleSprites()
        406->examples.sprites.AlignTextToSprite()
        407->examples.sprites.AlignToRectangle()
        408->examples.sprites.AlignToSprite()
        409->examples.sprites.AlignWithinSprite()
        410->examples.sprites.Anchor()
        411->examples.sprites.ChildSprites()
        412->examples.sprites.CollideWorldBounds()
        413->examples.sprites.Destroy()
        414->examples.sprites.DestroyTexture()
        415->examples.sprites.DynamicCrop()
        416->examples.sprites.FixedScale()
        417->examples.sprites.HorizontalCrop()
        418->examples.sprites.Mask()
        419->examples.sprites.MoveASprite()
        420->examples.sprites.MovementMask()
        421->examples.sprites.OutOfBounds()
        422->examples.sprites.OverlapTweenWithoutPhysics()
        423->examples.sprites.OverlapWithoutPhysics()
        424->examples.sprites.Pivot()
        425->examples.sprites.Rope()
        426->examples.sprites.RotateAndScale()
        427->examples.sprites.RotatedAtlasFrameSupport()
        428->examples.sprites.RotateSpriteAroundPoint()
        429->examples.sprites.ScaleASprite()
        430->examples.sprites.SharedSpriteTextures()
        431->examples.sprites.SpriteBounds()
        432->examples.sprites.SpriteDimensions()
        433->examples.sprites.SpriteFromBitmapdata()
        434->examples.sprites.SpriteGroupMask()
        435->examples.sprites.SpriteRotation()
        436->examples.sprites.Spritesheet()
        437->examples.sprites.SpriteTint()
        438->examples.sprites.VerticalCrop()
        439->examples.text.BitmapFontCacheAsBitmap()
        440->examples.text.BitmapfontDrag()
        441->examples.text.BitmapFontFromTextureAtlas()
        442->examples.text.BitmapFonts()
        443->examples.text.BitmaptextAnchorX()
        444->examples.text.BitmaptextAnchorY()
        445->examples.text.BitmaptextMaxWidth()
        446->examples.text.BitmaptextPurgeGlyphs()
        447->examples.text.BitmaptextWithPhysics()
        448->examples.text.BitmaptextWithPhysicsUpdating()
        449->examples.text.CenterText()
        450->examples.text.CenterTextOnSprite()
        451->examples.text.CleanText()
        452->examples.text.ColoredCharacters()
        453->examples.text.DisplayTextWordByWord()
        454->examples.text.DynamicTextShadow()
        455->examples.text.HelloArial()
        456->examples.text.KernOfDuty()
        457->examples.text.Littera()
        458->examples.text.RemoveText()
        459->examples.text.RetroFont1()
        460->examples.text.RetroFont2()
        461->examples.text.SetPropertiesAfterCreation()
        462->examples.text.TextBounds()
        463->examples.text.TextEvents()
        464->examples.text.TextGradient()
        465->examples.text.TextLineSpacing()
        466->examples.text.TextReflect()
        467->examples.text.TextShadowStroke()
        468->examples.text.TextStroke()
        469->examples.text.TextStrokeWithColor()
        470->examples.text.TextTabs()
        471->examples.text.TextTabsFromArray()
        472->examples.text.TextTint()
        473->examples.text.TextWithPhysics()
        474->examples.text.UpdateText()
        475->examples.text.WordWrap()
        476->examples.tilemaps.CreateFromArray()
        477->examples.tilemaps.CreateFromObjects()
        478->examples.tilemaps.CsvMap()
        479->examples.tilemaps.CsvMapCollide()
        480->examples.tilemaps.CsvMapWithP2()
        481->examples.tilemaps.DualView()
        482->examples.tilemaps.FeaturesTest()
        483->examples.tilemaps.FillTiles()
        484->examples.tilemaps.FlippedTiles()
        485->examples.tilemaps.MapBounce()
        486->examples.tilemaps.MapCollide()
        487->examples.tilemaps.Mario()
        488->examples.tilemaps.MultiLayer()
        489->examples.tilemaps.MultiLayerMultiTileset()
        490->examples.tilemaps.MultiMapCollide()
        491->examples.tilemaps.MultiTileset()
        492->examples.tilemaps.PaintTiles()
        493->examples.tilemaps.RandomiseTiles()
        494->examples.tilemaps.ReplaceTiles()
        495->examples.tilemaps.ResizeMap()
        496->examples.tilemaps.SciFly()
        497->examples.tilemaps.ShuffleTiles()
        498->examples.tilemaps.SwapTiles()
        499->examples.tilemaps.TileCallbacks()
        500->examples.tilemaps.TilemapRayCast()
        501->examples.tilemaps.TileProperties()
        502->examples.tilemaps.VerticalMap()
        503->examples.tilesprites.AnimatedTilingSprite()
        504->examples.tilesprites.CollidingWithTilingSprite()
        505->examples.tilesprites.SpriteSheetTilingSprite()
        506->examples.tilesprites.TileSpriteFromAnimatedSprite()
        507->examples.tilesprites.TilingAtlasTrim()
        508->examples.tilesprites.TilingSprite()
        509->examples.tilesprites.TilingSpriteAtlas()
        510->examples.tilesprites.TilingSpriteAtlas32x32()
        511->examples.time.BasicLoopedEvent()
        512->examples.time.BasicRepeatEvent()
        513->examples.time.BasicTimedEvent()
        514->examples.time.CustomTimer()
        515->examples.time.ElapsedSeconds()
        516->examples.time.MultipleTimers()
        517->examples.time.RemoveEvent()
        518->examples.time.TimedSlideshow()
        519->examples.tweens.AlphaText()
        520->examples.tweens.Bounce()
        521->examples.tweens.Bubbles()
        522->examples.tweens.ChainedTweens()
        523->examples.tweens.CombinedTweens()
        524->examples.tweens.Earthquake()
        525->examples.tweens.Easing()
        526->examples.tweens.EasingSpritesheets()
        527->examples.tweens.FadingInASprite()
        528->examples.tweens.GenerateData()
        529->examples.tweens.Interpolation()
        530->examples.tweens.PauseTween()
        531->examples.tweens.Repeat()
        532->examples.tweens.SingleTweenReuse()
        533->examples.tweens.TweenArray()
        534->examples.tweens.TweenDelay()
        535->examples.tweens.TweenFrom()
        536->examples.tweens.TweenLoopEvent()
        537->examples.tweens.TweenRelative()
        538->examples.tweens.TweenReuse()
        539->examples.tweens.TweenRotation()
        540->examples.tweens.TweenSeveralProperties()
        541->examples.tweens.TweenTo()
        542->examples.tweens.Yoyo()
        543->examples.video.AlphaWebm()
        544->examples.video.ChangeSource()
        545->examples.video.DolbyDigitalPlus()
        546->examples.video.LoadAsBlob()
        547->examples.video.MultipleVideos()
        548->examples.video.PlayVideo()
        549->examples.video.SnapshotBlendMode()
        550->examples.video.SpritesSharingVideo()
        551->examples.video.TakeSnapshotFromStream()
        552->examples.video.VideoStream()
        553->examples.weapon.Asteroids()
        554->examples.weapon.AsteroidsBulletWrap()
        555->examples.weapon.Autofire()
        556->examples.weapon.BulletAngleVariance()
        557->examples.weapon.BulletFrameCycle()
        558->examples.weapon.BulletSpeedVariance()
        559->examples.weapon.FireMany()
        560->examples.weapon.FireManyFromTrackedSprite()
        561->examples.weapon.FireManyWithVariance()
        562->examples.weapon.FireOffsetPosition()
        563->examples.weapon.FireRate()
        564->examples.weapon.MultipleBullets()
        565->examples.weapon.SingleBullet()
        566->examples.world.FixedToCamera()
        567->examples.world.MoveAroundWorld()
        568->examples.world.WorldWrap()

        else-> examples.basics.E01LoadAnImage()
    }
}

fun getExampleRenderer(exampleToRun: Int):Number {
    return when(exampleToRun){
        0->Phaser.AUTO
        1->Phaser.AUTO
        2->Phaser.CANVAS
        3->Phaser.CANVAS
        4->Phaser.AUTO
        5->Phaser.CANVAS
        6->Phaser.AUTO
        7->Phaser.CANVAS
        8->Phaser.AUTO
        9->Phaser.AUTO
        10->Phaser.AUTO
        11->Phaser.CANVAS
        12->Phaser.AUTO
        13->Phaser.AUTO
        14->Phaser.CANVAS
        15->Phaser.AUTO
        16->Phaser.CANVAS
        17->Phaser.CANVAS
        18->Phaser.CANVAS
        19->Phaser.CANVAS
        20->Phaser.CANVAS
        21->Phaser.AUTO
        22->Phaser.CANVAS
        23->Phaser.CANVAS
        24->Phaser.CANVAS
        25->Phaser.CANVAS
        26->Phaser.CANVAS
        27->Phaser.CANVAS
        28->Phaser.CANVAS
        29->Phaser.CANVAS
        30->Phaser.CANVAS
        31->Phaser.CANVAS
        32->Phaser.CANVAS
        33->Phaser.AUTO
        34->Phaser.AUTO
        35->Phaser.CANVAS
        36->Phaser.AUTO
        37->Phaser.CANVAS
        38->Phaser.CANVAS
        39->Phaser.CANVAS
        40->Phaser.CANVAS
        41->Phaser.CANVAS
        42->Phaser.CANVAS
        43->Phaser.CANVAS
        44->Phaser.AUTO
        45->Phaser.CANVAS
        46->Phaser.AUTO
        47->Phaser.AUTO
        48->Phaser.CANVAS
        49->Phaser.AUTO
        50->Phaser.CANVAS
        51->Phaser.CANVAS
        52->Phaser.CANVAS
        53->Phaser.CANVAS
        54->Phaser.CANVAS
        55->Phaser.CANVAS
        56->Phaser.CANVAS
        57->Phaser.CANVAS
        58->Phaser.CANVAS
        59->Phaser.AUTO
        60->Phaser.AUTO
        61->Phaser.AUTO
        62->Phaser.CANVAS
        63->Phaser.AUTO
        64->Phaser.AUTO
        65->Phaser.CANVAS
        66->Phaser.CANVAS
        67->Phaser.CANVAS
        68->Phaser.CANVAS
        69->Phaser.CANVAS
        70->Phaser.AUTO
        71->Phaser.CANVAS
        72->Phaser.CANVAS
        73->Phaser.CANVAS
        74->Phaser.CANVAS
        75->Phaser.CANVAS
        76->Phaser.AUTO
        77->Phaser.AUTO
        78->Phaser.AUTO
        79->Phaser.AUTO
        80->Phaser.AUTO
        81->Phaser.AUTO
        82->Phaser.CANVAS
        83->Phaser.CANVAS
        84->Phaser.CANVAS
        85->Phaser.AUTO
        86->Phaser.CANVAS
        87->Phaser.CANVAS
        88->Phaser.CANVAS
        89->Phaser.CANVAS
        90->Phaser.CANVAS
        91->Phaser.CANVAS
        92->Phaser.AUTO
        93->Phaser.AUTO
        94->Phaser.CANVAS
        95->Phaser.CANVAS
        96->Phaser.CANVAS
        97->Phaser.AUTO
        98->Phaser.AUTO
        99->Phaser.AUTO
        100->Phaser.CANVAS
        101->Phaser.AUTO
        102->Phaser.AUTO
        103->Phaser.AUTO
        104->Phaser.AUTO
        105->Phaser.AUTO
        106->Phaser.CANVAS
        107->Phaser.AUTO
        108->Phaser.CANVAS
        109->Phaser.CANVAS
        110->Phaser.CANVAS
        111->Phaser.CANVAS
        112->Phaser.CANVAS
        113->Phaser.CANVAS
        114->Phaser.CANVAS
        115->Phaser.CANVAS
        116->Phaser.AUTO
        117->Phaser.CANVAS
        118->Phaser.CANVAS
        119->Phaser.CANVAS
        120->Phaser.CANVAS
        121->Phaser.CANVAS
        122->Phaser.CANVAS
        123->Phaser.CANVAS
        124->Phaser.CANVAS
        125->Phaser.CANVAS
        126->Phaser.CANVAS
        127->Phaser.CANVAS
        128->Phaser.CANVAS
        129->Phaser.CANVAS
        130->Phaser.AUTO
        131->Phaser.CANVAS
        132->Phaser.CANVAS
        133->Phaser.CANVAS
        134->Phaser.CANVAS
        135->Phaser.AUTO
        136->Phaser.CANVAS
        137->Phaser.CANVAS
        138->Phaser.AUTO
        139->Phaser.AUTO
        140->Phaser.AUTO
        141->Phaser.AUTO
        142->Phaser.CANVAS
        143->Phaser.CANVAS
        144->Phaser.CANVAS
        145->Phaser.CANVAS
        146->Phaser.CANVAS
        147->Phaser.CANVAS
        148->Phaser.AUTO
        149->Phaser.AUTO
        150->Phaser.AUTO
        151->Phaser.AUTO
        152->Phaser.CANVAS
        153->Phaser.CANVAS
        154->Phaser.CANVAS
        155->Phaser.AUTO
        156->Phaser.AUTO
        157->Phaser.AUTO
        158->Phaser.CANVAS
        159->Phaser.WEBGL
        160->Phaser.CANVAS
        161->Phaser.CANVAS
        162->Phaser.AUTO
        163->Phaser.AUTO
        164->Phaser.CANVAS
        165->Phaser.AUTO
        166->Phaser.CANVAS
        167->Phaser.CANVAS
        168->Phaser.AUTO
        169->Phaser.AUTO
        170->Phaser.AUTO
        171->Phaser.WEBGL
        172->Phaser.WEBGL
        173->Phaser.AUTO
        174->Phaser.AUTO
        175->Phaser.AUTO
        176->Phaser.WEBGL
        177->Phaser.AUTO
        178->Phaser.WEBGL
        179->Phaser.AUTO
        180->Phaser.WEBGL
        181->Phaser.AUTO
        182->Phaser.WEBGL
        183->Phaser.AUTO
        184->Phaser.AUTO
        185->Phaser.AUTO
        186->Phaser.WEBGL
        187->Phaser.WEBGL
        188->Phaser.AUTO
        189->Phaser.AUTO
        190->Phaser.AUTO
        191->Phaser.AUTO
        192->Phaser.AUTO
        193->Phaser.AUTO
        194->Phaser.AUTO
        195->Phaser.AUTO
        196->Phaser.AUTO
        197->Phaser.AUTO
        198->Phaser.AUTO
        199->Phaser.AUTO
        200->Phaser.WEBGL
        201->Phaser.AUTO
        202->Phaser.AUTO
        203->Phaser.AUTO
        204->Phaser.AUTO
        205->Phaser.WEBGL
        206->Phaser.AUTO
        207->Phaser.CANVAS
        208->Phaser.CANVAS
        209->Phaser.AUTO
        210->Phaser.CANVAS
        211->Phaser.CANVAS
        212->Phaser.CANVAS
        213->Phaser.CANVAS
        214->Phaser.AUTO
        215->Phaser.AUTO
        216->Phaser.CANVAS
        217->Phaser.CANVAS
        218->Phaser.CANVAS
        219->Phaser.CANVAS
        220->Phaser.CANVAS
        221->Phaser.AUTO
        222->Phaser.CANVAS
        223->Phaser.CANVAS
        224->Phaser.CANVAS
        225->Phaser.CANVAS
        226->Phaser.CANVAS
        227->Phaser.CANVAS
        228->Phaser.CANVAS
        229->Phaser.CANVAS
        230->Phaser.CANVAS
        231->Phaser.CANVAS
        232->Phaser.CANVAS
        233->Phaser.CANVAS
        234->Phaser.CANVAS
        235->Phaser.CANVAS
        236->Phaser.CANVAS
        237->Phaser.CANVAS
        238->Phaser.CANVAS
        239->Phaser.CANVAS
        240->Phaser.CANVAS
        241->Phaser.CANVAS
        242->Phaser.CANVAS
        243->Phaser.CANVAS
        244->Phaser.AUTO
        245->Phaser.CANVAS
        246->Phaser.CANVAS
        247->Phaser.CANVAS
        248->Phaser.CANVAS
        249->Phaser.AUTO
        250->Phaser.AUTO
        251->Phaser.CANVAS
        252->Phaser.CANVAS
        253->Phaser.CANVAS
        254->Phaser.CANVAS
        255->Phaser.CANVAS
        256->Phaser.CANVAS
        257->Phaser.CANVAS
        258->Phaser.CANVAS
        259->Phaser.CANVAS
        260->Phaser.CANVAS
        261->Phaser.CANVAS
        262->Phaser.AUTO
        263->Phaser.CANVAS
        264->Phaser.CANVAS
        265->Phaser.CANVAS
        266->Phaser.CANVAS
        267->Phaser.CANVAS
        268->Phaser.CANVAS
        269->Phaser.CANVAS
        270->Phaser.CANVAS
        271->Phaser.CANVAS
        272->Phaser.AUTO
        273->Phaser.AUTO
        274->Phaser.CANVAS
        275->Phaser.CANVAS
        276->Phaser.CANVAS
        277->Phaser.CANVAS
        278->Phaser.CANVAS
        279->Phaser.AUTO
        280->Phaser.AUTO
        281->Phaser.AUTO
        282->Phaser.CANVAS
        283->Phaser.CANVAS
        284->Phaser.CANVAS
        285->Phaser.CANVAS
        286->Phaser.AUTO
        287->Phaser.AUTO
        288->Phaser.AUTO
        289->Phaser.AUTO
        290->Phaser.AUTO
        291->Phaser.CANVAS
        292->Phaser.CANVAS
        293->Phaser.CANVAS
        294->Phaser.CANVAS
        295->Phaser.CANVAS
        296->Phaser.CANVAS
        297->Phaser.CANVAS
        298->Phaser.CANVAS
        299->Phaser.AUTO
        300->Phaser.AUTO
        301->Phaser.AUTO
        302->Phaser.CANVAS
        303->Phaser.CANVAS
        304->Phaser.CANVAS
        305->Phaser.CANVAS
        306->Phaser.CANVAS
        307->Phaser.AUTO
        308->Phaser.CANVAS
        309->Phaser.CANVAS
        310->Phaser.CANVAS
        311->Phaser.CANVAS
        312->Phaser.CANVAS
        313->Phaser.CANVAS
        314->Phaser.CANVAS
        315->Phaser.CANVAS
        316->Phaser.AUTO
        317->Phaser.CANVAS
        318->Phaser.CANVAS
        319->Phaser.CANVAS
        320->Phaser.AUTO
        321->Phaser.CANVAS
        322->Phaser.AUTO
        323->Phaser.AUTO
        324->Phaser.CANVAS
        325->Phaser.AUTO
        326->Phaser.AUTO
        327->Phaser.CANVAS
        328->Phaser.AUTO
        329->Phaser.AUTO
        330->Phaser.CANVAS
        331->Phaser.CANVAS
        332->Phaser.CANVAS
        333->Phaser.AUTO
        334->Phaser.CANVAS
        335->Phaser.AUTO
        336->Phaser.CANVAS
        337->Phaser.AUTO
        338->Phaser.AUTO
        339->Phaser.CANVAS
        340->Phaser.AUTO
        341->Phaser.AUTO
        342->Phaser.CANVAS
        343->Phaser.AUTO
        344->Phaser.CANVAS
        345->Phaser.CANVAS
        346->Phaser.CANVAS
        347->Phaser.AUTO
        348->Phaser.AUTO
        349->Phaser.CANVAS
        350->Phaser.CANVAS
        351->Phaser.CANVAS
        352->Phaser.CANVAS
        353->Phaser.CANVAS
        354->Phaser.CANVAS
        355->Phaser.AUTO
        356->Phaser.CANVAS
        357->Phaser.CANVAS
        358->Phaser.CANVAS
        359->Phaser.CANVAS
        360->Phaser.CANVAS
        361->Phaser.CANVAS
        362->Phaser.CANVAS
        363->Phaser.CANVAS
        364->Phaser.CANVAS
        365->Phaser.CANVAS
        366->Phaser.CANVAS
        367->Phaser.AUTO
        368->Phaser.CANVAS
        369->Phaser.CANVAS
        370->Phaser.CANVAS
        371->Phaser.CANVAS
        372->Phaser.CANVAS
        373->Phaser.AUTO
        374->Phaser.AUTO
        375->Phaser.AUTO
        376->Phaser.AUTO
        377->Phaser.CANVAS
        378->Phaser.AUTO
        379->Phaser.AUTO
        380->Phaser.CANVAS
        381->Phaser.AUTO
        382->Phaser.AUTO
        383->Phaser.CANVAS
        384->Phaser.AUTO
        385->Phaser.CANVAS
        386->Phaser.AUTO
        387->Phaser.AUTO
        388->Phaser.CANVAS
        389->Phaser.AUTO
        390->Phaser.CANVAS
        391->Phaser.CANVAS
        392->Phaser.AUTO
        393->Phaser.AUTO
        394->Phaser.AUTO
        395->Phaser.CANVAS
        396->Phaser.AUTO
        397->Phaser.AUTO
        398->Phaser.AUTO
        399->Phaser.CANVAS
        400->Phaser.AUTO
        401->Phaser.AUTO
        402->Phaser.AUTO
        403->Phaser.AUTO
        404->Phaser.CANVAS
        405->Phaser.CANVAS
        406->Phaser.CANVAS
        407->Phaser.CANVAS
        408->Phaser.CANVAS
        409->Phaser.CANVAS
        410->Phaser.CANVAS
        411->Phaser.AUTO
        412->Phaser.AUTO
        413->Phaser.AUTO
        414->Phaser.AUTO
        415->Phaser.CANVAS
        416->Phaser.AUTO
        417->Phaser.AUTO
        418->Phaser.AUTO
        419->Phaser.CANVAS
        420->Phaser.AUTO
        421->Phaser.AUTO
        422->Phaser.CANVAS
        423->Phaser.CANVAS
        424->Phaser.CANVAS
        425->Phaser.AUTO
        426->Phaser.AUTO
        427->Phaser.CANVAS
        428->Phaser.CANVAS
        429->Phaser.AUTO
        430->Phaser.AUTO
        431->Phaser.CANVAS
        432->Phaser.AUTO
        433->Phaser.AUTO
        434->Phaser.AUTO
        435->Phaser.CANVAS
        436->Phaser.AUTO
        437->Phaser.CANVAS
        438->Phaser.AUTO
        439->Phaser.AUTO
        440->Phaser.AUTO
        441->Phaser.AUTO
        442->Phaser.AUTO
        443->Phaser.CANVAS
        444->Phaser.CANVAS
        445->Phaser.AUTO
        446->Phaser.AUTO
        447->Phaser.AUTO
        448->Phaser.AUTO
        449->Phaser.AUTO
        450->Phaser.CANVAS
        451->Phaser.AUTO
        452->Phaser.AUTO
        453->Phaser.CANVAS
        454->Phaser.CANVAS
        455->Phaser.CANVAS
        456->Phaser.AUTO
        457->Phaser.AUTO
        458->Phaser.CANVAS
        459->Phaser.AUTO
        460->Phaser.AUTO
        461->Phaser.AUTO
        462->Phaser.AUTO
        463->Phaser.CANVAS
        464->Phaser.CANVAS
        465->Phaser.CANVAS
        466->Phaser.CANVAS
        467->Phaser.CANVAS
        468->Phaser.CANVAS
        469->Phaser.CANVAS
        470->Phaser.CANVAS
        471->Phaser.CANVAS
        472->Phaser.CANVAS
        473->Phaser.AUTO
        474->Phaser.CANVAS
        475->Phaser.CANVAS
        476->Phaser.CANVAS
        477->Phaser.CANVAS
        478->Phaser.AUTO
        479->Phaser.CANVAS
        480->Phaser.CANVAS
        481->Phaser.CANVAS
        482->Phaser.AUTO
        483->Phaser.CANVAS
        484->Phaser.CANVAS
        485->Phaser.AUTO
        486->Phaser.CANVAS
        487->Phaser.AUTO
        488->Phaser.AUTO
        489->Phaser.CANVAS
        490->Phaser.CANVAS
        491->Phaser.CANVAS
        492->Phaser.CANVAS
        493->Phaser.CANVAS
        494->Phaser.CANVAS
        495->Phaser.AUTO
        496->Phaser.AUTO
        497->Phaser.CANVAS
        498->Phaser.CANVAS
        499->Phaser.AUTO
        500->Phaser.CANVAS
        501->Phaser.AUTO
        502->Phaser.CANVAS
        503->Phaser.CANVAS
        504->Phaser.CANVAS
        505->Phaser.CANVAS
        506->Phaser.CANVAS
        507->Phaser.CANVAS
        508->Phaser.CANVAS
        509->Phaser.CANVAS
        510->Phaser.CANVAS
        511->Phaser.CANVAS
        512->Phaser.CANVAS
        513->Phaser.CANVAS
        514->Phaser.CANVAS
        515->Phaser.CANVAS
        516->Phaser.CANVAS
        517->Phaser.CANVAS
        518->Phaser.CANVAS
        519->Phaser.WEBGL
        520->Phaser.AUTO
        521->Phaser.AUTO
        522->Phaser.AUTO
        523->Phaser.AUTO
        524->Phaser.AUTO
        525->Phaser.AUTO
        526->Phaser.AUTO
        527->Phaser.AUTO
        528->Phaser.AUTO
        529->Phaser.WEBGL
        530->Phaser.AUTO
        531->Phaser.AUTO
        532->Phaser.AUTO
        533->Phaser.AUTO
        534->Phaser.WEBGL
        535->Phaser.CANVAS
        536->Phaser.CANVAS
        537->Phaser.CANVAS
        538->Phaser.AUTO
        539->Phaser.CANVAS
        540->Phaser.AUTO
        541->Phaser.CANVAS
        542->Phaser.AUTO
        543->Phaser.CANVAS
        544->Phaser.CANVAS
        545->Phaser.CANVAS
        546->Phaser.CANVAS
        547->Phaser.CANVAS
        548->Phaser.CANVAS
        549->Phaser.CANVAS
        550->Phaser.AUTO
        551->Phaser.CANVAS
        552->Phaser.CANVAS
        553->Phaser.CANVAS
        554->Phaser.CANVAS
        555->Phaser.CANVAS
        556->Phaser.CANVAS
        557->Phaser.CANVAS
        558->Phaser.CANVAS
        559->Phaser.CANVAS
        560->Phaser.CANVAS
        561->Phaser.CANVAS
        562->Phaser.CANVAS
        563->Phaser.CANVAS
        564->Phaser.CANVAS
        565->Phaser.CANVAS
        566->Phaser.CANVAS
        567->Phaser.CANVAS
        568->Phaser.CANVAS

        else-> Phaser.AUTO
    }
}
